import type { Locale } from "@/lib/i18n/config";

/**
 * Human-readable measure names for the common WDI-style variant labels,
 * replacing raw dataset phrasing like "GDP: linked series (current LCU)".
 * Terms follow standard Persian economic usage (per fa.wikipedia.org:
 * "تعدیل‌شده با تورم" for inflation-adjusted / real values).
 *
 * Unrecognized labels pass through untouched; a proper measure-level naming
 * pass across all 1,842 charts is tracked as its own translation task.
 */
const RULES: {
  pattern: RegExp;
  en: string;
  fa: string;
  /** Append the base year ("(2015 prices)") when the raw label names one. */
  appendBaseYear?: boolean;
}[] = [
  // --- FAOSTAT measure names. The raw dataset labels are source jargon (LCU, SLC,
  // kcal/capita/day, "2014-2016 = 100"), which the owner flagged as unreadable.
  // The DATA keeps the source's own wording; only the DISPLAY is plain language.
  {
    pattern: /^Producer Price Index/i,
    en: "Producer price index (2014 to 2016 average = 100)",
    fa: "شاخص قیمت تولیدکننده (میانگین 2014 تا 2016 برابر 100)",
  },
  {
    pattern: /Producer Price \(LCU\/tonne\).*archive/i,
    en: "Producer price, local currency per tonne (FAO pre-1991 archive)",
    fa: "قیمت تولیدکننده، ریال بر تن (بایگانی پیش از 1991)",
  },
  {
    pattern: /Producer Price \(LCU\/tonne\)/i,
    en: "Producer price, local currency per tonne",
    fa: "قیمت تولیدکننده، ریال بر تن",
  },
  {
    pattern: /Producer Price \(SLC\/tonne\)/i,
    en: "Producer price, standardised local currency per tonne",
    fa: "قیمت تولیدکننده، پول ملی استاندارد بر تن",
  },
  {
    pattern: /Producer Price \(USD\/tonne\)/i,
    en: "Producer price, US dollars per tonne",
    fa: "قیمت تولیدکننده، دلار آمریکا بر تن",
  },
  {
    pattern: /Food supply \(kcal\/capita\/day\).*historic/i,
    en: "Food supply, calories per person per day (FAO historic series)",
    fa: "عرضه غذا، کالری به ازای هر نفر در روز (سری تاریخی فائو)",
  },
  {
    pattern: /Food supply \(kcal\/capita\/day\)/i,
    en: "Food supply, calories per person per day",
    fa: "عرضه غذا، کالری به ازای هر نفر در روز",
  },
  {
    pattern: /Food supply quantity \(kg\/capita\/yr\).*historic/i,
    en: "Food supply, kg per person per year (FAO historic series)",
    fa: "عرضه غذا، کیلوگرم به ازای هر نفر در سال (سری تاریخی فائو)",
  },
  {
    pattern: /Food supply quantity \(kg\/capita\/yr\)/i,
    en: "Food supply, kg per person per year",
    fa: "عرضه غذا، کیلوگرم به ازای هر نفر در سال",
  },
  {
    pattern: /Domestic supply quantity.*historic/i,
    en: "Domestic supply (FAO historic series)",
    fa: "عرضه داخلی (سری تاریخی فائو)",
  },
  { pattern: /Domestic supply quantity/i, en: "Domestic supply", fa: "عرضه داخلی" },
  {
    pattern: /^Producing Animals\/Slaughtered/i,
    en: "Animals slaughtered",
    fa: "دام‌های کشتارشده",
  },
  {
    pattern: /^Yield\/Carcass Weight/i,
    en: "Carcass weight per animal",
    fa: "وزن لاشه به ازای هر دام",
  },
  { pattern: /^Area harvested/i, en: "Area harvested", fa: "سطح زیر کشت" },
  { pattern: /^Export quantity/i, en: "Exports", fa: "صادرات" },
  { pattern: /^Import quantity/i, en: "Imports", fa: "واردات" },
  { pattern: /^Milk Animals/i, en: "Milk animals", fa: "دام‌های شیرده" },
  { pattern: /^Stocks$/i, en: "Livestock stocks", fa: "موجودی دام" },
  { pattern: /^Yield$/i, en: "Yield", fa: "عملکرد" },
  { pattern: /^Production$/i, en: "Production", fa: "تولید" },
  {
    // Methodology (build_currency_variants.py): deflated by the country's
    // OWN price index, then expressed in base-year dollars — never US CPI.
    pattern: /constant\s+(\d{4}\s+)?(international\s+)?US?\$|constant.*U\.?S\.? dollars/i,
    en: "US dollars, adjusted for inflation",
    fa: "دلار آمریکا، تعدیل‌شده با تورم",
    appendBaseYear: true,
  },
  {
    pattern: /current\s+(international\s+)?US?\$|current.*U\.?S\.? dollars/i,
    en: "US dollars, not adjusted for inflation",
    fa: "دلار آمریکا، بدون تعدیل تورم",
  },
  {
    // Iran-centric charts: LCU means the rial. (Comparator-country LCU
    // handling is the separate currency-layer task.)
    pattern: /constant\s+LCU/i,
    en: "Rial, adjusted for Iran's inflation",
    fa: "ریال، تعدیل‌شده با تورم",
    appendBaseYear: true,
  },
  {
    pattern: /current\s+LCU/i,
    en: "Rial, not adjusted for inflation",
    fa: "ریال، بدون تعدیل تورم",
  },
];

function baseYearSuffix(rawLabel: string, locale: Locale): string {
  const m = rawLabel.match(/constant\s+(\d{4})/i);
  if (!m) return "";
  return locale === "fa" ? ` (قیمت‌های ${m[1]})` : ` (${m[1]} prices)`;
}

// Generated by the variant-label translation agent (Wikipedia-fa terminology):
// exact-label lookups for the dropdown/measure labels the rules above miss.
import labelsMapJson from "./variant-labels-map.json";
const LABELS_MAP: Record<string, { fa?: string; en?: string }> =
  (labelsMapJson as { labels?: Record<string, { fa?: string; en?: string }> })
    .labels ?? {};

export function friendlyVariantLabel(rawLabel: string, locale: Locale): string {
  for (const rule of RULES) {
    if (rule.pattern.test(rawLabel)) {
      return (
        rule[locale] + (rule.appendBaseYear ? baseYearSuffix(rawLabel, locale) : "")
      );
    }
  }
  const mapped = LABELS_MAP[rawLabel.trim()];
  if (mapped) {
    if (locale === "fa" && mapped.fa) return mapped.fa;
    if (mapped.en) return mapped.en;
  }
  // House style: em dashes never reach the UI, even from raw dataset labels.
  const comma = locale === "fa" ? "، " : ", ";
  return rawLabel.replace(/\s*[—–]\s*/g, comma);
}

/**
 * Default measure for a chart. For currency charts the black-market
 * (parallel) rate is the honest headline number, so it wins over the
 * official rate whenever present.
 */
export function pickDefaultVariant(
  variants: { code: string; label: string }[]
): string {
  const parallel = variants.find((v) =>
    /parallel|black[\s_-]?market|بازار\s*آزاد/i.test(`${v.code} ${v.label}`)
  );
  return (parallel ?? variants[0])?.code ?? "";
}
